services:
  db:
    container_name: rust-postgres
    image: postgres
    ports:
      - '5431:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postGr3s1245xSDI
      POSTGRES_DB: rust_app_db
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata: {}
